### ISSUE TITLE
Actions が main ブランチのPRを探して NotFound エラーを出す

### ISSUE THREAD

**Issue by 1ntegrale9** [DiscordBotPortalJP/database#19]
https://github.com/DiscordBotPortalJP/database/runs/1271101000

```
Run flake8 --ignore=E501 . | lintly --format=flake8 --log --commit-sha=
  flake8 --ignore=E501 . | lintly --format=flake8 --log --commit-sha=
  shell: /bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.6/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.6/x64/lib
    LINTLY_API_KEY: ***
Lintly: 2020-10-18 12:29:02,432 [DEBUG] lintly.builds: Using the following configuration:

Lintly: 2020-10-18 12:29:02,433 [DEBUG] lintly.builds:   - pr='main'
Lintly: 2020-10-18 12:29:02,433 [DEBUG] lintly.builds:   - repo='DiscordBotPortalJP/database'
Lintly: 2020-10-18 12:29:02,433 [DEBUG] lintly.builds:   - commit_sha='89f1c6d1387b58761cdbb1446bd1b2e51dc227dc'
Lintly: 2020-10-18 12:29:02,433 [DEBUG] lintly.builds:   - api_key='********'
Lintly: 2020-10-18 12:29:02,433 [DEBUG] lintly.builds:   - format='flake8'
Lintly: 2020-10-18 12:29:02,433 [DEBUG] lintly.builds:   - fail_on='any'
Lintly: 2020-10-18 12:29:02,433 [DEBUG] lintly.builds:   - post_status=True
Lintly: 2020-10-18 12:29:02,433 [DEBUG] lintly.builds:   - request_changes=True
Lintly: 2020-10-18 12:29:02,433 [DEBUG] lintly.builds:   - github_check_run_id='313724567'
Lintly: 2020-10-18 12:29:02,433 [INFO] lintly.builds: Running Lintly against PR #main for repo DiscordBotPortalJP/database
Lintly: 2020-10-18 12:29:02,433 [INFO] lintly.builds: Lintly found violations in 0 files
Lintly: 2020-10-18 12:29:02,434 [DEBUG] lintly.backends.github: Sending a get request to /repos/DiscordBotPortalJP/database/pulls/main
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.6/x64/bin/lintly", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/lintly/cli.py", line 74, in main
    build.execute()
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/lintly/builds.py", line 76, in execute
    diff = self.get_pr_diff()
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/lintly/builds.py", line 86, in get_pr_diff
    return self.git_client.get_pr_diff(self.config.pr)
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/lintly/backends/github.py", line 171, in get_pr_diff
    diff = client.get(diff_url, headers={'Accept': GITHUB_DIFF_HEADER})
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/lintly/backends/github.py", line 85, in get
    return self._do_request('get', url, data, headers)
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/lintly/backends/github.py", line 112, in _do_request
    raise NotFoundError(response.content, status_code=response.status_code)
lintly.backends.errors.NotFoundError: b'{"message":"Not Found","documentation_url":"https://docs.github.com/rest/reference/pulls#get-a-pull-request"}'
Error: Process completed with exit code 1.
```

**Comment by Shirataki2** [comment]
mainへのPush時にエラーが起きてるみたいなので削除するPRを出します．

Flake8のノリで条件を書いたら思わぬところでエラーが発生してしまいました．お騒がせしました 🙏
